### ISSUE TITLE
For consistency, change all components from html to nunjucks

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-common-templates#8]
We made a decision a while back to tell people to use Nunjucks for components. It would make sense and be less confusing to change all components in the templates from html to nunjucks

This PR already starts the transition to Nunjucks, but is specific to one template:
- https://github.com/alphagov/govuk-prototype-kit-docs/pull/159

**Comment by nataliecarey** [comment]
I've done this as part of the work in progress for supporting `.njk` - all our files will be updated to `.njk` as part of that PR (in its current form)

**Comment by joelanman** [comment]
@nataliecarey this is to convert the html code of the components in the templates to use nunjucks macros instead - isn't that separate from the .njk extension work?

**Comment by nataliecarey** [comment]
Sorry, I forgot they'd been moved out to their own project :)

Yes, I think we should make this change - to be clear we're talking about _templates_ rather than _components_ right?  Templates can be renamed any time, components would have to wait until we've finished that work.

**Comment by joelanman** [comment]
no worries, it's gov.uk components within templates so stuff like back link and buttons - no renaming at all. See the Check answers PR above for an example - it switches to the summary list macro from html.

**Comment by ruthhammond** [comment]
@nataliecarey to review whether this needs to happen after njk change
